/**  insert 数据 */
-- 字典表新增数据
insert into `sys_dict` (`id`, `dict_parent_code`, `dict_code`, `dict_name`, `dict_value`, `dict_status`, `dict_memo`, `is_leaf`, `dict_parent_id`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `order_number`, `value_flag`) values('124',NULL,'tag_update_frequency','标签更新频率','','1','标签更新频率','1',NULL,NULL,NULL,now(),NULL,now(),'0',NULL,NULL,'1',NULL);
insert into `sys_dict` (`id`, `dict_parent_code`, `dict_code`, `dict_name`, `dict_value`, `dict_status`, `dict_memo`, `is_leaf`, `dict_parent_id`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `order_number`, `value_flag`) values('125','tag_update_frequency','every_day','每天','1','1','','0',NULL,NULL,NULL,now(),NULL,now(),'0',NULL,NULL,'1',NULL);
insert into `sys_dict` (`id`, `dict_parent_code`, `dict_code`, `dict_name`, `dict_value`, `dict_status`, `dict_memo`, `is_leaf`, `dict_parent_id`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `order_number`, `value_flag`) values('126','tag_update_frequency','three_day','3天','3','1','','0',NULL,NULL,NULL,now(),NULL,now(),'0',NULL,NULL,'2',NULL);
insert into `sys_dict` (`id`, `dict_parent_code`, `dict_code`, `dict_name`, `dict_value`, `dict_status`, `dict_memo`, `is_leaf`, `dict_parent_id`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `order_number`, `value_flag`) values('127','tag_update_frequency','seven_day','7天','7','1','','0',NULL,NULL,NULL,now(),NULL,now(),'0',NULL,NULL,'3',NULL);
insert into `sys_dict` (`id`, `dict_parent_code`, `dict_code`, `dict_name`, `dict_value`, `dict_status`, `dict_memo`, `is_leaf`, `dict_parent_id`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `order_number`, `value_flag`) values('128','tag_update_frequency','every_month','每月','30','1','','0',NULL,NULL,NULL,now(),NULL,now(),'0',NULL,NULL,'4',NULL);
insert into `sys_dict` (`id`, `dict_parent_code`, `dict_code`, `dict_name`, `dict_value`, `dict_status`, `dict_memo`, `is_leaf`, `dict_parent_id`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `order_number`, `value_flag`) values('129',NULL,'life_cycle','生命周期运算符',NULL,'1','生命周期运算符','1',NULL,NULL,NULL,now(),NULL,NULL,'0',NULL,NULL,'1',NULL);
insert into `sys_dict` (`id`, `dict_parent_code`, `dict_code`, `dict_name`, `dict_value`, `dict_status`, `dict_memo`, `is_leaf`, `dict_parent_id`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `order_number`, `value_flag`) values('130','life_cycle','life_cycle_greater_than','大于','> ?','1','生命周期运算符-大于','0',NULL,NULL,NULL,now(),NULL,now(),'0',NULL,NULL,'1',NULL);
insert into `sys_dict` (`id`, `dict_parent_code`, `dict_code`, `dict_name`, `dict_value`, `dict_status`, `dict_memo`, `is_leaf`, `dict_parent_id`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `order_number`, `value_flag`) values('131','life_cycle','life_cycle_situated_between','介于','>= ? AND ? <=','1','生命周期运算符-介于','0',NULL,NULL,NULL,now(),NULL,now(),'0',NULL,NULL,'2',NULL);
insert into `sys_dict` (`id`, `dict_parent_code`, `dict_code`, `dict_name`, `dict_value`, `dict_status`, `dict_memo`, `is_leaf`, `dict_parent_id`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `order_number`, `value_flag`) values('132',NULL,'tag_type','标签类型',NULL,'1','标签类型','1',NULL,NULL,NULL,now(),NULL,now(),'0',NULL,NULL,'1',NULL);
insert into `sys_dict` (`id`, `dict_parent_code`, `dict_code`, `dict_name`, `dict_value`, `dict_status`, `dict_memo`, `is_leaf`, `dict_parent_id`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `order_number`, `value_flag`) values('133','tag_type','tag_type_0','会员','0','1','标签类型-会员','0',NULL,NULL,NULL,now(),NULL,now(),'0',NULL,NULL,'1',NULL);
insert into `sys_dict` (`id`, `dict_parent_code`, `dict_code`, `dict_name`, `dict_value`, `dict_status`, `dict_memo`, `is_leaf`, `dict_parent_id`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `order_number`, `value_flag`) values('134','tag_type','tag_type_1','粉丝','1','1','标签类型-粉丝','0',NULL,NULL,NULL,now(),NULL,now(),'0',NULL,NULL,'2',NULL);

-- 标签分类表新增自定义标签  指定id 系统配置需要
insert into `sys_tag_classes` (`id`, `tag_classes_code`, `tag_classes_name`, `tag_classes_status`, `tag_classes_memo`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`) values('8',NULL,'自定义标签','0','自定义标签（不对前端展示）',NULL,NULL,now(),NULL,now(),'0',NULL,NULL);

-- 菜单数据
insert into `sys_menu` (`id`, `menu_name`, `brands_id`, `menu_lev`, `menu_parent_id`, `menu_route`, `menu_status`, `menu_order`, `menu_memo`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `is_button`, `button_name`, `icon`) values('219','自定义标签',NULL,NULL,'9','/tagManage/casual','1','3','',NULL,'1',NOW(),'1',NOW(),'0',NULL,NULL,'0',NULL,'folder-o');
insert into `sys_menu` (`id`, `menu_name`, `brands_id`, `menu_lev`, `menu_parent_id`, `menu_route`, `menu_status`, `menu_order`, `menu_memo`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `is_button`, `button_name`, `icon`) values('220','模型分析',NULL,NULL,'0','','1','6','',NULL,'1',now(), '2',NOW(),'0',null,NULL,'0',NULL,'folder-o');
insert into `sys_menu` (`id`, `menu_name`, `brands_id`, `menu_lev`, `menu_parent_id`, `menu_route`, `menu_status`, `menu_order`, `menu_memo`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `is_button`, `button_name`, `icon`) values('221','生命周期模型列表',NULL,NULL,'220','/lifeManage/index','1','1','',NULL,'1',NOW(),'1',NOW(),'0',NULL,NULL,'0',NULL,'folder-o');
insert into `sys_menu` (`menu_name`, `brands_id`, `menu_lev`, `menu_parent_id`, `menu_route`, `menu_status`, `menu_order`, `menu_memo`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `is_button`, `button_name`, `icon`) values('/sysTagPropertyUser/export',NULL,NULL,'11','/tag','1','1','这是按钮',NULL,NULL,NOW(),'1',NOW(),'0',NULL,NULL,'1','/tag/sysTagPropertyUser/export','icon图标');
insert into `sys_menu` (`menu_name`, `brands_id`, `menu_lev`, `menu_parent_id`, `menu_route`, `menu_status`, `menu_order`, `menu_memo`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `is_button`, `button_name`, `icon`) values('/tagCustomiz/save',NULL,NULL,'219','/tag','1','1','这是按钮',NULL,NULL,NOW(),'1',NOW(),'0',NULL,NULL,'1','/tag/tagCustomiz/save','icon图标');
insert into `sys_menu` (`menu_name`, `brands_id`, `menu_lev`, `menu_parent_id`, `menu_route`, `menu_status`, `menu_order`, `menu_memo`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `is_button`, `button_name`, `icon`) values('/tagCustomiz/update',NULL,NULL,'219','/tag','1','1','这是按钮',NULL,NULL,NOW(),NULL,NOW(),'0',NULL,NULL,'1','/tag/tagCustomiz/update','icon图标');
insert into `sys_menu` (`menu_name`, `brands_id`, `menu_lev`, `menu_parent_id`, `menu_route`, `menu_status`, `menu_order`, `menu_memo`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `is_button`, `button_name`, `icon`) values('/tagCustomiz/getListByPage',NULL,NULL,'219','/tag','1','1','这是按钮',NULL,NULL,NOW(),NULL,NOW(),'0',NULL,NULL,'1','/tag/tagCustomiz/getListByPage','icon图标');
insert into `sys_menu` (`menu_name`, `brands_id`, `menu_lev`, `menu_parent_id`, `menu_route`, `menu_status`, `menu_order`, `menu_memo`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `is_button`, `button_name`, `icon`) values('/tagCustomiz/delete/',NULL,NULL,'219','/tag','1','1','这是按钮',NULL,NULL,NOW(),NULL,NOW(),'0',NULL,NULL,'1','/tag/tagCustomiz/delete/','icon图标');
insert into `sys_menu` (`menu_name`, `brands_id`, `menu_lev`, `menu_parent_id`, `menu_route`, `menu_status`, `menu_order`, `menu_memo`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `is_button`, `button_name`, `icon`) values('/tagCustomiz/downloadTemplate',NULL,NULL,'219','/tag','1','1','这是按钮',NULL,NULL,NOW(),NULL,NOW(),'0',NULL,NULL,'1','/tag/tagCustomiz/downloadTemplate','icon图标');
insert into `sys_menu` (`menu_name`, `brands_id`, `menu_lev`, `menu_parent_id`, `menu_route`, `menu_status`, `menu_order`, `menu_memo`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `is_button`, `button_name`, `icon`) values('/tagGroupUser/getTableInfo',NULL,NULL,'4','/tag','1','1','这是按钮',NULL,'1',NOW(),'1',NOW(),'0',NULL,NULL,'1','/tag/tagGroupUser/getTableInfo','icon图标');
insert into `sys_menu` (`menu_name`, `brands_id`, `menu_lev`, `menu_parent_id`, `menu_route`, `menu_status`, `menu_order`, `menu_memo`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `is_button`, `button_name`, `icon`) values('/tagGroupUser/getChartInfo',NULL,NULL,'4','/tag','1','1','这是按钮',NULL,'1',NOW(),'1',NOW(),'0',NULL,NULL,'1','/tag/tagGroupUser/getChartInfo','icon图标');
insert into `sys_menu` (`menu_name`, `brands_id`, `menu_lev`, `menu_parent_id`, `menu_route`, `menu_status`, `menu_order`, `menu_memo`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `is_button`, `button_name`, `icon`) values('/sysSynchronizationConfig/getMainDatabaseTableField',NULL,NULL,'8','/data','1','1','这是按钮',NULL,'1',NOW(),'1',NOW(),'0',NULL,NULL,'1','/data/sysSynchronizationConfig/getMainDatabaseTableField','icon图标');
insert into `sys_menu` (`menu_name`, `brands_id`, `menu_lev`, `menu_parent_id`, `menu_route`, `menu_status`, `menu_order`, `menu_memo`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `is_button`, `button_name`, `icon`) values('/sysSynchronizationConfig/getMainDatabaseTableName',NULL,NULL,'8','/data','1','1','这是按钮',NULL,'1',NOW(),'1',NOW(),'0',NULL,NULL,'1','/data/sysSynchronizationConfig/getMainDatabaseTableName','icon图标');
insert into `sys_menu` (`menu_name`, `brands_id`, `menu_lev`, `menu_parent_id`, `menu_route`, `menu_status`, `menu_order`, `menu_memo`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `is_button`, `button_name`, `icon`) values('/lifeCycle/getList',NULL,NULL,'221','/tag','1','1','这是按钮',NULL,'1',NOW(),'1',NOW(),'0',NULL,NULL,'1','/tag/lifeCycle/getList','icon图标');
insert into `sys_menu` (`menu_name`, `brands_id`, `menu_lev`, `menu_parent_id`, `menu_route`, `menu_status`, `menu_order`, `menu_memo`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `is_button`, `button_name`, `icon`) values('/lifeCycle/save',NULL,NULL,'221','/tag','1','1','这是按钮',NULL,'1',NOW(),'1',NOW(),'0',NULL,NULL,'1','/tag/lifeCycle/save','icon图标');
insert into `sys_menu` (`menu_name`, `brands_id`, `menu_lev`, `menu_parent_id`, `menu_route`, `menu_status`, `menu_order`, `menu_memo`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `is_button`, `button_name`, `icon`) values('/lifeCycle/modify',NULL,NULL,'221','/tag','1','1','这是按钮',NULL,'1',NOW(),'1',NOW(),'0',NULL,NULL,'1','/tag/lifeCycle/modify','icon图标');
insert into `sys_menu` (`menu_name`, `brands_id`, `menu_lev`, `menu_parent_id`, `menu_route`, `menu_status`, `menu_order`, `menu_memo`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `is_button`, `button_name`, `icon`) values('/lifeCycle/getRule/',NULL,NULL,'221','/tag','1','1','这是按钮',NULL,'1',NOW(),'1',NOW(),'0',NULL,NULL,'1','/tag/lifeCycle/getRule/','icon图标');
insert into `sys_menu` (`menu_name`, `brands_id`, `menu_lev`, `menu_parent_id`, `menu_route`, `menu_status`, `menu_order`, `menu_memo`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `is_button`, `button_name`, `icon`) values('/lifeCycle/delete/',NULL,NULL,'221','/tag','1','1','这是按钮',NULL,'1',NOW(),'1',NOW(),'0',NULL,NULL,'1','/tag/lifeCycle/delete/','icon图标');
insert into `sys_menu` (`menu_name`, `brands_id`, `menu_lev`, `menu_parent_id`, `menu_route`, `menu_status`, `menu_order`, `menu_memo`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `is_button`, `button_name`, `icon`) values('/sysBrands/getAvgRepurchaseCycle/',NULL,NULL,'17','/auth','1','1','这是按钮',NULL,'1',NOW(),'1',NOW(),'0',NULL,NULL,'1','/auth/sysBrands/getAvgRepurchaseCycle/','icon图标');
insert into `sys_menu` (`menu_name`, `brands_id`, `menu_lev`, `menu_parent_id`, `menu_route`, `menu_status`, `menu_order`, `menu_memo`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `is_button`, `button_name`, `icon`) values('/sysSynchronizationConfig/getOrgDatabase',NULL,NULL,'8','/data','1','1','这是按钮',NULL,'1',NOW(),'1',NOW(),'0',NULL,NULL,'1','/data/sysSynchronizationConfig/getOrgDatabase','icon图标');
insert into `sys_menu` (`menu_name`, `brands_id`, `menu_lev`, `menu_parent_id`, `menu_route`, `menu_status`, `menu_order`, `menu_memo`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `is_button`, `button_name`, `icon`) values('/test/getAllTopic',NULL,NULL,'7','/data','1','1','这是按钮',NULL,'1',now(),'1',NOW(),'0',NULL,NULL,'1','/data/test/getAllTopic','icon图标');
insert into `sys_menu` (`menu_name`, `brands_id`, `menu_lev`, `menu_parent_id`, `menu_route`, `menu_status`, `menu_order`, `menu_memo`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `is_button`, `button_name`, `icon`) values('/test/createTopic',NULL,NULL,'7','/data','1','1','这是按钮',NULL,'1',now(),'1',NOW(),'0',NULL,NULL,'1','/data/test/createTopic','icon图标');
insert into `sys_menu` (`menu_name`, `brands_id`, `menu_lev`, `menu_parent_id`, `menu_route`, `menu_status`, `menu_order`, `menu_memo`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `is_button`, `button_name`, `icon`) values('/sysTagPropertyUser/file/upload',NULL,NULL,'11','/tag','1','1','这是按钮',NULL,'1', NOW(),'1',NOW(),'0',NULL,NULL,'1','/tag/sysTagPropertyUser/file/upload','icon图标');
insert into `sys_menu` (`menu_name`, `brands_id`, `menu_lev`, `menu_parent_id`, `menu_route`, `menu_status`, `menu_order`, `menu_memo`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `is_button`, `button_name`, `icon`) values('/woaap/orgInfoList',NULL,NULL,'16','/auth','1','1','这是按钮',NULL,NULL,NOW(),NULL,NOW(),'0',NULL,NULL,'1','/auth/woaap/orgInfoList','icon图标');
insert into `sys_menu` (`menu_name`, `brands_id`, `menu_lev`, `menu_parent_id`, `menu_route`, `menu_status`, `menu_order`, `menu_memo`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `is_button`, `button_name`, `icon`) values('/woaap/brandManageInfo',NULL,NULL,'17','/auth','1','1','这是按钮',NULL,NULL,NOW(),NULL,NOW(),'0',NULL,NULL,'1','/auth/woaap/brandManageInfo','icon图标');
insert into `sys_menu` (`menu_name`, `brands_id`, `menu_lev`, `menu_parent_id`, `menu_route`, `menu_status`, `menu_order`, `menu_memo`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `is_button`, `button_name`, `icon`) values('/tag/woaap/getBrandsAppIds',NULL,NULL,'11','/tag','1','1','这是按钮',NULL,NULL,NOW(),NULL,NOW(),'0',NULL,NULL,'1','/tag/tag/woaap/getBrandsAppIds','icon图标');
insert into `sys_menu` (`menu_name`, `brands_id`, `menu_lev`, `menu_parent_id`, `menu_route`, `menu_status`, `menu_order`, `menu_memo`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `is_button`, `button_name`, `icon`) values('/sysColumn/save',NULL,NULL,'7','/data','1','1','这是按钮',NULL,NULL,now(),NULL,now(),'0',NULL,NULL,'1','/data/sysColumn/save','icon图标');
insert into `sys_menu` (`menu_name`, `brands_id`, `menu_lev`, `menu_parent_id`, `menu_route`, `menu_status`, `menu_order`, `menu_memo`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `is_button`, `button_name`, `icon`) values('/sysColumn/delete/',NULL,NULL,'7','/data','1','1','这是按钮',NULL,NULL,now(),NULL,now(),'0',NULL,NULL,'1','/data/sysColumn/delete/','icon图标');
insert into `sys_menu` (`menu_name`, `brands_id`, `menu_lev`, `menu_parent_id`, `menu_route`, `menu_status`, `menu_order`, `menu_memo`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `is_button`, `button_name`, `icon`) values('/sysColumn/update',NULL,NULL,'7','/data','1','1','这是按钮',NULL,NULL,now(),NULL,now(),'0',NULL,NULL,'1','/data/sysColumn/update','icon图标');
insert into `sys_menu` (`menu_name`, `brands_id`, `menu_lev`, `menu_parent_id`, `menu_route`, `menu_status`, `menu_order`, `menu_memo`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `is_button`, `button_name`, `icon`) values('/sysColumn/list',NULL,NULL,'7','/data','1','1','这是按钮',NULL,NULL,now(),NULL,now(),'0',NULL,NULL,'1','/data/sysColumn/list','icon图标');
insert into `sys_menu` (`menu_name`, `brands_id`, `menu_lev`, `menu_parent_id`, `menu_route`, `menu_status`, `menu_order`, `menu_memo`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`, `is_button`, `button_name`, `icon`) values('/sysColumn/cache',NULL,NULL,'7','/data','1','1','这是按钮',NULL,NULL,now(),NULL,now(),'0',NULL,NULL,'1','/data/sysColumn/cache','icon图标');
-- 给管理员角色添加菜单权限
INSERT INTO `sys_role_permission`(`menu_id`, `role_id`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`) VALUES ( 219, 1, NULL, 1, now(), 1, now(), 0, NULL, NULL);
INSERT INTO `sys_role_permission`(`menu_id`, `role_id`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`) VALUES ( 220, 1, NULL, 1, now(), 1, now(), 0, NULL, NULL);
INSERT INTO `sys_role_permission`(`menu_id`, `role_id`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`) VALUES ( 221, 1, NULL, 1, now(), 1, now(), 0, NULL, NULL);

-- 加工规则
insert into `sys_etl_processing_rule` (`name`, `status`, `param_table`, `param_column`, `processing_sql`, `target_table`, `target_columns`, `target_where_column`, `target_where_column_value_source`, `update_size`, `query_size`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`) values('会员基础信息','1','members','id','SELECT id,TIMESTAMPDIFF(YEAR,birthday,CURDATE()) age,MONTH(birthday) birth_month,DAY(birthday) birth_day FROM members WHERE id #{whereParam};','members','age,birth_month,birth_day','id','id','1000','5000',NULL,NULL,now(),NULL,now(),'0',NULL,NULL);
insert into `sys_etl_processing_rule` (`name`, `status`, `param_table`, `param_column`, `processing_sql`, `target_table`, `target_columns`, `target_where_column`, `target_where_column_value_source`, `update_size`, `query_size`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`) values('会员门店信息','1','members','storeno','SELECT shop_code storeno,TYPE store_type,province store_province,city store_city,district store_district  FROM  `t_shops` WHERE org_id=#{orgId} and brands_id =#{brandsId} and status=1 AND shop_code #{whereParam};','members','store_type,store_province,store_city,store_district','id','id','1000','5000',NULL,NULL,now(),NULL,now(),'0',NULL,NULL);
insert into `sys_etl_processing_rule` (`name`, `status`, `param_table`, `param_column`, `processing_sql`, `target_table`, `target_columns`, `target_where_column`, `target_where_column_value_source`, `update_size`, `query_size`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`) values('会员消费信息','1','members','member_id','SELECT *, ROUND(consume_amount/order_goods_num,2) unit_price,ROUND(order_goods_num/order_count,2) customer_order_goods_num,ROUND(consume_amount/order_count,2) customer_order_price FROM (SELECT member_id, MIN(pay_time) first_consume_time,MAX(pay_time) last_consume_time,IFNULL(SUM(pay_amount),0) AS consume_amount,IFNULL(SUM(pay_amount),0) pay_amount,IFNULL(SUM(goods_number),0) order_goods_num, COUNT(DISTINCT orderno) order_count,is_delete FROM t_orders  WHERE is_delete=0 AND org_id=#{orgId} and brands_id=#{brandsId} and order_type=1 AND member_id #{whereParam} group by member_id) t1 ;','members','first_consume_time,last_consume_time,consume_amount,pay_amount,order_goods_num,order_count,unit_price,customer_order_goods_num,customer_order_price','id','id','1000','5000',NULL,NULL,now(),NULL,now(),'0',NULL,NULL);
insert into `sys_etl_processing_rule` (`name`, `status`, `param_table`, `param_column`, `processing_sql`, `target_table`, `target_columns`, `target_where_column`, `target_where_column_value_source`, `update_size`, `query_size`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`) values('会员一年内消费信息','1','members','member_id','SELECT member_id,IFNULL(SUM(pay_amount),0) recent_year_consume_amount,IFNULL(SUM(pay_amount),0) recent_year_pay_amount,COUNT(DISTINCT orderno) recent_year_order_count FROM t_orders WHERE org_id=#{orgId} and brands_id=#{brandsId} and order_type=1 AND member_id #{whereParam} and DATEDIFF(NOW(),pay_time)<=365 group by member_id;','members','recent_year_consume_amount,recent_year_pay_amount,recent_year_order_count','id','id','1000','5000',NULL,NULL,now(),NULL,now(),'0',NULL,NULL);
insert into `sys_etl_processing_rule` (`name`, `status`, `param_table`, `param_column`, `processing_sql`, `target_table`, `target_columns`, `target_where_column`, `target_where_column_value_source`, `update_size`, `query_size`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`) values('会员手机号','1','members','id','SELECT id,1 mobile_available   FROM members WHERE id #{whereParam} and mobile REGEXP \"^[1]([3-9])[0-9]{9}$\";','members','mobile_available','id','id','1000','5000',NULL,NULL,now(),NULL,now(),'0',NULL,NULL);
insert into `sys_etl_processing_rule` (`name`, `status`, `param_table`, `param_column`, `processing_sql`, `target_table`, `target_columns`, `target_where_column`, `target_where_column_value_source`, `update_size`, `query_size`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`) values('订单门店信息(sql 有limit 1,updateSize 只能是1)','1','t_shops','shop_code','SELECT shop_code, TYPE store_type,province store_province,city store_city,district store_district  FROM  `t_shops` WHERE org_id=#{orgId} and brands_id=#{brandsId} AND shop_code #{whereParam} order by shop_id desc limit 1;','t_orders','store_type,store_province,store_city,store_district','storeno','shop_code','1','9',NULL,NULL,now(),NULL,now(),'0',NULL,NULL);
insert into `sys_etl_processing_rule` (`name`, `status`, `param_table`, `param_column`, `processing_sql`, `target_table`, `target_columns`, `target_where_column`, `target_where_column_value_source`, `update_size`, `query_size`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`) values('粉丝表','1','wechat_user','id','select  id,1 as is_member from `wechat_user` w  where  exists (select 1 from members m where m.org_id=#{orgId} and m.brands_id =#{brandsId} and w.wechat_unionid=m.unionid) and id #{whereParam};','wechat_user','is_member','id','id','1000','5000',NULL,NULL,now(),NULL,now(),'0',NULL,NULL);
insert into `sys_etl_processing_rule` (`name`, `status`, `param_table`, `param_column`, `processing_sql`, `target_table`, `target_columns`, `target_where_column`, `target_where_column_value_source`, `update_size`, `query_size`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`) values('会员是否是粉丝字段','1','members','id','SELECT  id,1 AS is_wechat_user FROM `members` m  WHERE  EXISTS (SELECT 1 FROM wechat_user w WHERE w.org_id=#{orgId} and w.brands_id =#{brandsId} and w.wechat_unionid=m.unionid) and id #{whereParam};','members','is_wechat_user','id','id','1000','5000',NULL,NULL,now(),NULL,now(),'0',NULL,NULL);

/* update 数据 */
-- 系统标签 品牌机构设置默认值
update `sys_tag`  set org_id=1,brands_id=1;
-- 标签更新频率字典id  set 初始值 需要根据频率的字典id 来
update `sys_tag` SET tag_update_frequency_dict_id=125;
-- 更新标签下次执行时间，set 成当前时间
update `sys_tag` SET tag_next_update_date=now() where is_delete=0;

-- 更新admin用户的品牌
update `sys_user` set  organization=1,brands_id=1 where id=1;

-- 更新字典 由 原来的数据源标识 改成 会员/粉丝 标识
UPDATE sys_dict set dict_name = '粉丝库' where id=108;
UPDATE sys_dict set dict_name = '会员库' where id=109;

-- set 系统配置
insert into `sys_column` (`classes_id`, `column_code`, `column_value`, `column_name`, `column_memo`, `column_status`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`) values(NULL,'','1','sysOrgId','系统机构ID','1','0',NULL,now(),NULL,now(),'0',NULL,NULL);
insert into `sys_column` (`classes_id`, `column_code`, `column_value`, `column_name`, `column_memo`, `column_status`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`) values(NULL,NULL,'1','sysBrandsId','系统品牌ID','1','0',NULL,now(),NULL,now(),'0',NULL,NULL);
insert into `sys_column` (`classes_id`, `column_code`, `column_value`, `column_name`, `column_memo`, `column_status`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`) values(NULL,NULL,'10000','deletetotal','标签ETL删除最大条数','1','0',NULL,now(),NULL,now(),'0',NULL,NULL);
insert into `sys_column` (`classes_id`, `column_code`, `column_value`, `column_name`, `column_memo`, `column_status`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`) values(NULL,NULL,'10000','writer_max_number','标签ETL写入最大条数','1','0',NULL,now(),NULL,now(),'0',NULL,NULL);
insert into `sys_column` (`classes_id`, `column_code`, `column_value`, `column_name`, `column_memo`, `column_status`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`) values(NULL,NULL,'10000','max_number','标签ETL写入用户最大条数','1','0',NULL,now(),NULL,now(),'0',NULL,NULL);
insert into `sys_column` (`classes_id`, `column_code`, `column_value`, `column_name`, `column_memo`, `column_status`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`) values(NULL,NULL,'0 0 1 * * ?','dataUpdateCron','标签数据自动更新 cron','1','0',NULL,now(),NULL,now(),'0',NULL,NULL);
insert into `sys_column` (`classes_id`, `column_code`, `column_value`, `column_name`, `column_memo`, `column_status`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`) values(NULL,NULL,'8','customizTagClassesId','自定义标签分类id','1','0',NULL,now(),NULL,now(),'0',NULL,NULL);
insert into `sys_column` (`classes_id`, `column_code`, `column_value`, `column_name`, `column_memo`, `column_status`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`) values(NULL,NULL,'[\"mobile\",\"number\",\"unionid\",\"openid\"]','whereCaseColumn','自定义标签查询列','1','0',NULL,now(),NULL,now(),'0',NULL,NULL);
insert into `sys_column` (`classes_id`, `column_code`, `column_value`, `column_name`, `column_memo`, `column_status`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`) values(NULL,NULL,'手机号/会员号/unionid/openid','templateHeader','自定义标签下载模板头','1','0',NULL,now(),NULL,now(),'0',NULL,NULL);
insert into `sys_column` (`classes_id`, `column_code`, `column_value`, `column_name`, `column_memo`, `column_status`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`) values(NULL,NULL,'20000','query_max_number','etl数据同步读取最大条数','1','0',NULL,now(),NULL,now(),'0',NULL,NULL);
insert into `sys_column` (`classes_id`, `column_code`, `column_value`, `column_name`, `column_memo`, `column_status`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`) values(NULL,NULL,'eto_crm_sys','masterTableSchema','目标库库名','1','0',NULL,now(),NULL,now(),'0',NULL,NULL);
insert into `sys_column` (`classes_id`, `column_code`, `column_value`, `column_name`, `column_memo`, `column_status`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`) values(NULL,NULL,'4','kafkaPartitionCount','kafka分区数量','1','0',NULL,now(),NULL,now(),'0',NULL,NULL);
insert into `sys_column` (`classes_id`, `column_code`, `column_value`, `column_name`, `column_memo`, `column_status`, `revision`, `created_by`, `created_time`, `updated_by`, `updated_time`, `is_delete`, `delete_by`, `delete_time`) values(NULL,NULL,'500','youngorDataSaveSize','保存雅戈尔标签数据单次最多支持条数','0','0',NULL,now(),NULL,now(),'0',NULL,NULL);

-- insert 雅戈尔访问接口的key
INSERT INTO `mat_automation_visit_auth_records` (`sys_code`, `app_name`, `api_url`, `request_ip`, `access_key`, `secret_key`, `status`, `REVISION`, `CREATED_BY`, `CREATED_TIME`, `UPDATED_BY`, `UPDATED_TIME`, `delete_by`, `is_delete`, `delete_time`) VALUES(NULL,NULL,'/tag/tag/saveYoungorData','0:0:0:0:0:0:0:1','d5f683ec1ca4989fc26ab403485288fb','eed8b812a71772508f563d21ecade977','0',NULL,NULL,NOW(),NULL,NOW(),NULL,'1',NULL);